version: 2

multi-ecosystem-groups:
  all-dependencies:
    schedule:
      interval: "monthly"
      time: "08:00"
      timezone: "America/Bahia"

updates:
  - package-ecosystem: "npm"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "all-dependencies"
